name: XSkyBlock
version: 1.0
main: com.xskyblock.XSkyBlock
api-version: 1.17
depend: [Vault, WorldEdit]
commands:
  xmi:
    description: Main command for XSkyBlock plugin
    usage: /<command> [subcommand]
    aliases: [xskyblock, xisland]
permissions:
  xskyblock.admin:
    description: Allows access to admin commands
    default: op